### ISSUE TITLE
Threshold not comming through.

### ISSUE THREAD

**Issue by bpjbauch** [louy/terraform-provider-uptimerobot#34]
Hi, 
Maybe I'm doing it wrong, but I can't get the threshold to work via terraform.
I'm on a pro plan and can set the threshold and recurrence via the web frontend, but when I set them in the .tf file it does not come through.
I'm using the provider built from the master branch.

```
resource "uptimerobot_monitor" "mycheckname" {
  url            = "http://mysitetomonitor.example.com"
  type           = "http"
  friendly_name  = "mycheckname"
  interval       = 60
  alert_contact {
    id = "${data.uptimerobot_alert_contact.default_alert_contact.id}"
    threshold  = 5
    recurrence = 0
  } 
```

**Comment by drubin** [comment]
Heya @bpjbauch 
Is this a new `alert_contact` or old? I think there was an issue about updating existing alert contact's `threshold ` or `recurrence` values.

I added this feature and it seems to be working pretty well for *new* monitors / alert_contact  so just trying to figure out if the editing part might be broken?

**Comment by bpjbauch** [comment]
Ah thanks, this explains a lot.
Yes it is an old `alert_contact`. We are testing the PagerDuty integration, which is not public yet and had to bei provided by the UptimeRobots them self, so I can't re-create this.

**Comment by louy** [comment]
sadly with UR's api there's on way to import alert contacts, which is why this will break for you.
what you can do is manually change your TF state file to add these values in, but other than that we can't really do anything

another thing you might want to try is adding support for PD as an alert contact since you're building from master anyway, and it might make things easier for you

**Comment by louy** [comment]
@all-contributors please add @bpjbauch for bug report
